### ISSUE TITLE
fatal error when used with jetpack

### ISSUE THREAD

**Issue by ameesters** [hoducha/wp-markdown-editor#3]
Hello, i just tried to install your plugin, the notes said that if you wanted to use it with jetpack you first needed to activate jetpack, and then the plugin... well i did just that but now i am getting a fatal error:

> Fatal error: Cannot redeclare class WPCom_Markdown in /var/www/vhosts/m-id.me/httpdocs/wp-content/plugins/wp-markdown-editor/jetpack/markdown/easy-markdown.php on line 34

since its a fatal error, the plugin staid disabled :-(

**Comment by hoducha** [comment]
Hello ameesters,

You should deactivate the Markdown module from Jetpack settings.

Explanation: The plugin uses Jetpack Markdown module for parsing and saving contents. The module is included in the plugin in order to make it works independently. So, you could not activate the plugin if the Jetpack Markdown module is activated.

I will update the plugin to detect if the Jetpack Markdown module is activated in the next release.

**Comment by hoducha** [comment]
The plugin was updated to prevent error if Jetpack Markdown module is activated.
